name: build_windows

on:
  release:
    types: [published]
  push:
    branches:
      - master  

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run pack:prepare
    - run: npm run pack:win:publish
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Upload Release Asset-Zip
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: rdm/build/windows/installer/resp-${{ env.VERSION }}.zip
        asset_name: resp-${{ env.VERSION }}.zip
        asset_content_type: application/zip
