name: build_windows

on:
  release:
    types: [published]
  push:
    branches:
      - master  

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Get current date
      id: date
      run: echo "CURRENTDATE=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run pack:prepare
    - run: npm run pack:win
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        path: dist/build-apps/win-unpacked
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: nightly-${{ steps.date.outputs.date }}
        commit: master
        token: ${{ secrets.GITHUB_TOKEN }}     
